spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/eco-meter
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: eco-meter
    password: eco-meter

  flyway:
    url: jdbc:hsqldb:hsql://localhost:9001/eco-meter
    user: eco-meter
    password: eco-meter
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none