CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);


CREATE TABLE usage_measurement
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id          BIGINT         NOT NULL,
    gas_usage        DECIMAL(15, 5) NOT NULL,
    cold_water_usage DECIMAL(15, 5) NOT NULL,
    hot_water_usage  DECIMAL(15, 5) NOT NULL,
    issued_at        TIMESTAMP      NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_user_id ON usage_measurement(user_id);

-- insert data for unit tests
INSERT INTO users DEFAULT
VALUES;
INSERT INTO usage_measurement(user_id, gas_usage, cold_water_usage, hot_water_usage, issued_at)
VALUES (0, 1, 1, 1, now);


