CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
);


CREATE TABLE usage_measurement
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id          BIGINT         NOT NULL,
    gas_usage        DECIMAL(15, 5) NOT NULL,
    cold_water_usage DECIMAL(15, 5) NOT NULL,
    hot_water_usage  DECIMAL(15, 5) NOT NULL,
    issued_at        TIMESTAMP      NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- insert several users into system
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;

